import {
    collection,
    doc,
    addDoc,
    updateDoc,
    deleteDoc,
    query,
    where,
    getDocs,
    orderBy,
    serverTimestamp
} from "firebase/firestore";
import { db } from "../lib/firebase";
import { Contact } from "../types";

const COLLECTION_NAME = "contacts";

// We will store contacts in a subcollection: users/{userId}/contacts/{contactId}
// This acts as a security boundary and logical grouping.

export const ContactService = {
    // Add a new contact
    addContact: async (userId: string, contact: Contact): Promise<Contact> => {
        try {
            // Remove id from contact data before adding (Firestore generates one, or we use the one present)
            // Actually, if we want to use the QR-provided ID, we should use setDoc.
            // But QR IDs might be timestamps or UUIDs generated by invalid client.
            // Better to let Firestore generate ID or use the one we have if robust.
            // For now, let's use addDoc to auto-generate, or setDoc if we trust the ID.
            // Given offline/sync needs, robust UUIDs are better.
            // Let's use the ID in the contact object if it exists and looks valid, otherwise generate.

            const contactData = { ...contact, userId, createdAt: serverTimestamp() };
            delete (contactData as any).id; // Don't save ID as a field inside if redundant, but useful for JSON access

            const userContactsRef = collection(db, "users", userId, "contacts");

            // If we want to preserve the ID from the QR code (if it acts as a UUID)
            // we would use doc(userContactsRef, contact.id).
            // However, duplication handling?
            // Let's rely on Firestore auto-ID for storage key, but keep external ID in data?
            // Simple: use addDoc.

            const docRef = await addDoc(userContactsRef, contactData);
            return { ...contact, id: docRef.id };
        } catch (error) {
            console.error("Error adding contact:", error);
            throw error;
        }
    },

    // Get all contacts for a user
    getContacts: async (userId: string): Promise<Contact[]> => {
        try {
            const userContactsRef = collection(db, "users", userId, "contacts");
            const q = query(userContactsRef, orderBy("dateMet", "desc")); // Order by dateMet or createdAt
            const querySnapshot = await getDocs(q);

            return querySnapshot.docs.map(doc => ({
                ...(doc.data() as Omit<Contact, 'id'>),
                id: doc.id
            }));
        } catch (error) {
            console.error("Error getting contacts:", error);
            throw error;
        }
    },

    // Update a contact
    updateContact: async (userId: string, contact: Contact): Promise<void> => {
        try {
            if (!contact.id) throw new Error("Contact ID missing");
            const contactRef = doc(db, "users", userId, "contacts", contact.id);

            const { id, ...updateData } = contact; // Exclude ID from update
            await updateDoc(contactRef, updateData as any);
        } catch (error) {
            console.error("Error updating contact:", error);
            throw error;
        }
    },

    // Delete a contact
    deleteContact: async (userId: string, contactId: string): Promise<void> => {
        try {
            const contactRef = doc(db, "users", userId, "contacts", contactId);
            await deleteDoc(contactRef);
        } catch (error) {
            console.error("Error deleting contact:", error);
            throw error;
        }
    }
};
